### ISSUE TITLE
利用Github Pages搭建个人主页的全过程

### ISSUE THREAD

**Issue by Niu-Liu** [Niu-Liu/Niu-Liu.github.io#6]
https://niu-liu.github.io/create_blog_with_github_pages/ 

 这是我的个人主页搭建完成之后的第一篇博文，整个搭建过程花了四天时间，现在我记录下搭建过程，
包括我的需求和实现、遇到的问题和解决方法。
需要声明的是，这并不是一篇教程，它展示的是我瞎折腾的过程，仅作自娱自乐之用。
而对于搭建教程，我推荐这篇
《可能是最全面的github pages搭建个人博客教程》。
实际上，我也借鉴了这位作者的模版。

我参考了以下模版：

  
    academicpages，
  适合于学术展示；
  
  
    lemonchann，
  非常简洁的博客模版；
  
  
    particle
  和jekyll-uno-timeline，
  我很喜欢他们的首页风格。
  

由于我的个人需求，最终我的个人主页就是囊括这三类模版的“缝合怪”。
如果你在寻找合适的模版，可以参考我上面的推荐。

**Comment by Niu-Liu** [comment]
测试一下

**Comment by bigbyto-anon** [comment]
测试一下

**Comment by bigbyto-anon** [comment]
Test

**Comment by bigbyto-anon** [comment]
谢谢刘博的分享！超详细的教程，有心了～
